app:
  name: 'Template'
  version: '0.0.0'
  build: 'dev'

http:
  port: '1000'

logger:
  log_level: 'debug'
  rollbar_env: 'catalog_m'

#nats:
#  NATS_URL: 'nats://nats:4222'
#  NATS_THEME: 'module'
#  NATS_TIMER: '2'

ent_pg:
#  PG_URL: 'postgres://user:pass@postgres:5432/postgres'
  ENT_PG_HOST: 'localhost'
  ENT_PG_PORT: '5432'
  ENT_PG_USER: 'user'
  ENT_PG_PASSWORD: 'pass'
  ENT_PG_DATABASE: 'postgres'


