app:
  name: 'Template'
  version: '0.0.1'
  build: 'dev'

http:
  port: '1000'

logger:
  log_level: 'debug'
  rollbar_env: 'catalog_m'

nats:
  NATS_URL: 'nats://nats:4222'
  NATS_THEME: '2'
  NATS_TIMER: '2'

pg:
  PG_URL: 'postgres://2:pass@postgres:5432/postgres'


