// Code generated by ent, DO NOT EDIT.

package ent

import (
	"git.legchelife.ru/root/template/ent/schema"
	"git.legchelife.ru/root/template/ent/task"
	"git.legchelife.ru/root/template/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescAge is the schema descriptor for age field.
	taskDescAge := taskFields[1].Descriptor()
	// task.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	task.AgeValidator = taskDescAge.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[1].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
}
