// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/module/block/get/test": {
            "get": {
                "security": [
                    {
                        "Token-A": []
                    }
                ],
                "description": "Метод для получения списка категорий",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog/Category"
                ],
                "summary": "getTest - получить категории",
                "operationId": "module.block.get",
                "responses": {
                    "200": {
                        "description": "Возвращает список категорий",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Возвращает ошибку",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Token-A": {
            "type": "apiKey",
            "name": "Token-A",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0",
	Host:             "localhost:1000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "TEMPLATE",
	Description:      "Шаблон для создания нового сервиса",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
