basePath: /v1
host: localhost:1000
info:
  contact: {}
  description: API для работы с каталогом и контентом сайта каталога
  title: CATALOG API123123
  version: "1.0"
paths:
  /module/block/get/test:
    get:
      description: Метод для получения списка категорий
      operationId: module.block.get
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает список категорий
          schema:
            type: string
        "500":
          description: Возвращает ошибку
          schema:
            type: string
      security:
      - Token-A: []
      summary: getTest - получить категории
      tags:
      - Catalog/Category
securityDefinitions:
  Token-A:
    in: header
    name: Token-A
    type: apiKey
swagger: "2.0"
